CREATE TABLE GRUPPE (id VARCHAR NOT NULL, bezeichnung VARCHAR NOT NULL, PRIMARY KEY (id))
CREATE TABLE BEITRAG (renderzeitpunkt TIMESTAMP, TITLE VARCHAR, navigationspfad VARCHAR NOT NULL, ablagepfad VARCHAR NOT NULL, navigationkey VARCHAR NOT NULL, PROJEKTNAME VARCHAR, REPOSITORYNAME VARCHAR, VCSURL VARCHAR, VCSVERSION VARCHAR, PRIMARY KEY (navigationspfad, ablagepfad));
CREATE TABLE HAUPTNAVIGATION (gruppeId VARCHAR NOT NULL, hauptnavigationname VARCHAR NOT NULL, SORTIERUNG INTEGER, PRIMARY KEY (gruppeId, hauptnavigationname));
CREATE TABLE SEITENNAVIGATION (navigationspfad VARCHAR NOT NULL, gruppeId VARCHAR NOT NULL, hauptnavigationname VARCHAR NOT NULL, PRIMARY KEY (navigationspfad));
CREATE TABLE KATEGORIE (KATEGORIENAME VARCHAR NOT NULL, PRIMARY KEY (KATEGORIENAME));
CREATE TABLE BEITRAGSKATEGORIE (navigationspfad VARCHAR NOT NULL, ablagepfad VARCHAR NOT NULL, KATEGORIENAME VARCHAR NOT NULL, PRIMARY KEY (navigationspfad, ablagepfad, KATEGORIENAME));
ALTER TABLE BEITRAG ADD CONSTRAINT navigationkey_unique UNIQUE(navigationkey);
ALTER TABLE GRUPPE ADD CONSTRAINT gruppebezeichnung_unique UNIQUE(bezeichnung);
ALTER TABLE HAUPTNAVIGATION ADD CONSTRAINT HAUPTNAVIGATIONGRUPPEgruppeid FOREIGN KEY (gruppeId) REFERENCES GRUPPE (id);
ALTER TABLE SEITENNAVIGATION ADD CONSTRAINT SEITENNAVIGATIONHAUPTNAVIGATIONhauptnavigationname FOREIGN KEY (hauptnavigationname, gruppeId) REFERENCES HAUPTNAVIGATION (hauptnavigationname, gruppeId);
ALTER TABLE BEITRAGSKATEGORIE ADD CONSTRAINT FK_BEITRAGSKATEGORIE_navigationspfad FOREIGN KEY (navigationspfad, ablagepfad) REFERENCES BEITRAG (navigationspfad, ablagepfad);
ALTER TABLE BEITRAGSKATEGORIE ADD CONSTRAINT FK_BEITRAGSKATEGORIE_kategorien_KATEGORIENAME FOREIGN KEY (KATEGORIENAME) REFERENCES KATEGORIE (KATEGORIENAME);